Hit the api
rebaz36/Leaderboard-API pull request #2
Opened 2022-08-31 21:58 UTC by rebaz36

2022-08-31 22:16 UTC, Whoistolu requested changes
Hi @rebaz36 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

### N/A

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-31 22:16 UTC, Whoistolu commented on src/modules/mainClass.js
> +      .catch(() => new Error('Error in newPost'));
- [ ] [REQUIRED] Great implementation @rebaz36, however, you need to use the `async` and `await` with the fetch method to send and receive data as stated by the [project requirement](https://github.com/microverseinc/curriculum-javascript/blob/main/leaderboard/m2_send_receive_data.md).

2022-09-01 03:16 UTC, rebaz36 commented on src/modules/mainClass.js
> +      .catch(() => new Error('Error in newPost'));
Thanks @Whoistolu, i seem to have missed this requirement when reading the project details.
appreciate you bringing this to my attention

2022-09-01 03:18 UTC, rloterh commented on src/modules/mainClass.js
> +      .catch(() => new Error('Error in newPost'));
This is well resolved! ✔️

2022-09-01 03:21 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Rebaz,  

Your project is complete! There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉🌟 

## Highlights 👍
- Promise feature properly implemented

<br>
Keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-01 13:55 UTC, merged